# Generated by Django 4.2.27 on 2026-01-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hsk_level', models.IntegerField()),
                ('total_days', models.IntegerField(default=30)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['hsk_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_minutes', models.IntegerField(default=15)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='course.course')),
            ],
            options={
                'verbose_name': 'Course Day',
                'verbose_name_plural': 'Course Days',
                'ordering': ['course', 'day_number'],
                'unique_together': {('course', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('MIXED', 'Mixed')], default='MIXED', max_length=20)),
                ('hsk_level', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('title_zh', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.courseday')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course_day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('VOCAB_INTRO', 'Vocabulary Introduction'), ('VOCAB_RECOGNIZE', 'Vocabulary Recognition'), ('VOCAB_MATCH', 'Vocabulary Matching'), ('GRAMMAR_INTRO', 'Grammar Introduction'), ('BUILD_PHRASE', 'Build Phrase'), ('FILL_BLANK', 'Fill in the Blank'), ('SRS_REVIEW', 'SRS Review')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_rules', models.ManyToManyField(blank=True, related_name='lesson_steps', to='vocab.grammarrule')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='course.lesson')),
                ('words', models.ManyToManyField(blank=True, related_name='lesson_steps', to='vocab.word')),
            ],
            options={
                'verbose_name': 'Lesson Step',
                'verbose_name_plural': 'Lesson Steps',
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
