# Generated by Django 6.0.1 on 2026-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseday',
            name='grammar_rules',
            field=models.ManyToManyField(blank=True, related_name='course_days', to='vocab.grammarrule'),
        ),
        migrations.AddField(
            model_name='courseday',
            name='new_words',
            field=models.ManyToManyField(blank=True, related_name='course_days', to='vocab.word'),
        ),
    ]
