# Generated by Django 4.2.27 on 2026-01-27 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRSBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('word_ids', models.JSONField(default=list)),
                ('total_words', models.IntegerField(default=0)),
                ('reviews_completed', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SRS Batch',
                'verbose_name_plural': 'SRS Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step_index', models.IntegerField(default=0)),
                ('steps_completed', models.IntegerField(default=0)),
                ('steps_correct', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.courseday')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Progress',
                'verbose_name_plural': 'Session Progress',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.lessonstep')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='learning.sessionprogress')),
            ],
            options={
                'verbose_name': 'Lesson Step Progress',
                'verbose_name_plural': 'Lesson Step Progress',
                'ordering': ['session', 'lesson_step__order'],
                'unique_together': {('session', 'lesson_step')},
            },
        ),
    ]
