# Generated by Django 6.0.1 on 2026-01-28 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseday_grammar_rules_courseday_new_words'),
        ('learning', '0001_initial'),
        ('vocab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionprogress',
            name='course_day',
        ),
        migrations.RemoveField(
            model_name='sessionprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='sessionprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='srsbatch',
            name='user',
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('A', 'Session A'), ('B', 'Session B')], max_length=1)),
                ('lines', models.JSONField(default=list)),
                ('question_hanzi', models.TextField()),
                ('question_pinyin', models.TextField()),
                ('question_translation_ru', models.TextField()),
                ('question_translation_kz', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('options', models.JSONField(default=list)),
                ('explanation_ru', models.TextField(blank=True)),
                ('explanation_kz', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='course.courseday')),
            ],
            options={
                'verbose_name': 'Dialogue',
                'verbose_name_plural': 'Dialogues',
                'ordering': ['course_day', 'session_type', 'order'],
                'unique_together': {('course_day', 'session_type', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GrammarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('A', 'Session A'), ('B', 'Session B')], max_length=1)),
                ('task_prompt_ru', models.TextField()),
                ('task_prompt_kz', models.TextField()),
                ('components', models.JSONField(default=list)),
                ('correct_hanzi', models.TextField()),
                ('correct_pinyin', models.TextField()),
                ('correct_translation_ru', models.TextField()),
                ('correct_translation_kz', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_tasks', to='course.courseday')),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='vocab.grammarrule')),
            ],
            options={
                'verbose_name': 'Grammar Task',
                'verbose_name_plural': 'Grammar Tasks',
                'ordering': ['course_day', 'session_type', 'order'],
                'unique_together': {('course_day', 'session_type', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('A', 'Session A'), ('B', 'Session B')], max_length=1)),
                ('current_step', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('step_1_started_at', models.DateTimeField(blank=True, null=True)),
                ('step_1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_2_started_at', models.DateTimeField(blank=True, null=True)),
                ('step_2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_3_started_at', models.DateTimeField(blank=True, null=True)),
                ('step_3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_4_started_at', models.DateTimeField(blank=True, null=True)),
                ('step_4_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_5_started_at', models.DateTimeField(blank=True, null=True)),
                ('step_5_completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('words_learned', models.IntegerField(default=0)),
                ('problematic_words', models.JSONField(default=list)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='course.courseday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Session',
                'verbose_name_plural': 'Learning Sessions',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'course_day', 'session_type')},
            },
        ),
        migrations.CreateModel(
            name='NewWordLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('pronunciation_attempts', models.IntegerField(default=0)),
                ('pronunciation_ok_count', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_word_progress', to='learning.learningsession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='vocab.word')),
            ],
            options={
                'verbose_name': 'New Word Learning Progress',
                'verbose_name_plural': 'New Word Learning Progress',
                'ordering': ['session', 'created_at'],
                'unique_together': {('session', 'word')},
            },
        ),
        migrations.CreateModel(
            name='SRSReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=list)),
                ('selected_option_id', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('is_problematic', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='learning.learningsession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='vocab.word')),
            ],
            options={
                'verbose_name': 'SRS Review Card',
                'verbose_name_plural': 'SRS Review Cards',
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('SRS_REVIEW', 'Step 1: SRS Review'), ('NEW_WORDS', 'Step 2: New Words'), ('GRAMMAR', 'Step 3: Grammar'), ('DIALOGUE', 'Step 4: Dialogue'), ('WORD_ARRANGEMENT', 'Step 5: Word Arrangement')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='learning.learningsession')),
            ],
            options={
                'verbose_name': 'Step Progress',
                'verbose_name_plural': 'Step Progress',
                'ordering': ['session', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='WordArrangementExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('A', 'Session A'), ('B', 'Session B')], max_length=1)),
                ('target_hanzi', models.TextField()),
                ('target_pinyin', models.TextField()),
                ('target_translation_ru', models.TextField()),
                ('target_translation_kz', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('scrambled_words', models.JSONField(default=list)),
                ('hint_ru', models.TextField(blank=True)),
                ('hint_kz', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangement_exercises', to='course.courseday')),
            ],
            options={
                'verbose_name': 'Word Arrangement Exercise',
                'verbose_name_plural': 'Word Arrangement Exercises',
                'ordering': ['course_day', 'session_type', 'order'],
                'unique_together': {('course_day', 'session_type', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='LessonStepProgress',
        ),
        migrations.DeleteModel(
            name='SessionProgress',
        ),
        migrations.DeleteModel(
            name='SRSBatch',
        ),
    ]
