# Generated by Django 6.0.1 on 2026-02-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_fix_user_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded video file', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('url', 'URL Link'), ('file', 'Uploaded File')], default='url', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', max_length=500),
        ),
    ]
