# Generated by Django 6.0.1 on 2026-02-10 11:00

from django.db import migrations, models


def migrate_video_types(apps, schema_editor):
    """Set video_type to 'url' for existing NULL records"""
    Video = apps.get_model('video', 'Video')
    Video.objects.filter(video_type__isnull=True).update(video_type='url')


def reverse_migrate_video_types(apps, schema_editor):
    """Reverse migration - set all to NULL"""
    Video = apps.get_model('video', 'Video')
    Video.objects.all().update(video_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_thumbnail_video_video_file_video_video_type_and_more'),
    ]

    operations = [
        # First, migrate existing data
        migrations.RunPython(migrate_video_types, reverse_migrate_video_types),
        # Then make field nullable
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(
                blank=True,
                choices=[('file', 'Uploaded File'), ('url', 'URL Link')],
                max_length=20,
                null=True
            ),
        ),
    ]
