# Generated by Django 6.6.1 on 2026-02-10 16:18

from django.db import migrations, models


def fix_render_database(apps, schema_editor):
    """
    Fix Render database structure if needed.
    This migration ensures compatibility between old and new database states.
    Uses raw SQL for PostgreSQL compatibility.
    """
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Make video_type nullable if it exists and is NOT NULL
            cursor.execute("""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'video_video'
                        AND column_name = 'video_type'
                        AND is_nullable = 'NO'
                    ) THEN
                        ALTER TABLE video_video ALTER COLUMN video_type DROP NOT NULL;
                    END IF;
                END $$;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_thumbnail_video_video_file_video_video_type_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_render_database, migrations.RunPython.noop),
    ]
