# Generated by Django 6.0.1 on 2026-02-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_thumbnail_video_video_file_video_video_type_and_more'),
    ]

    operations = [
        # Make video_type nullable for backward compatibility
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(
                blank=True,
                choices=[('file', 'Uploaded File'), ('url', 'URL Link')],
                default='url',
                max_length=20,
                null=True
            ),
        ),
    ]
