# Generated by Django 6.0.1 on 2026-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_thumbnail_video_video_file_video_video_type_and_more'),
    ]

    operations = [
        # Make video_type nullable for backward compatibility
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(
                choices=[('url', 'URL Link'), ('file', 'Uploaded File')],
                blank=True,
                default='url',
                max_length=20,
                null=True
            ),
        ),
        # Add default values for URL fields
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube, Vimeo, etc.', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
