# Generated by Django 6.0.1 on 2026-02-10 17:01

from django.db import migrations, models


def add_missing_fields(apps, schema_editor):
    """
    Add video_file and thumbnail fields if they don't exist (for Render compatibility).
    Uses raw SQL for PostgreSQL compatibility.
    """
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Add video_file column if it doesn't exist
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'video_video'
                        AND column_name = 'video_file'
                    ) THEN
                        ALTER TABLE video_video ADD COLUMN video_file VARCHAR(100) NULL;
                    END IF;
                END $$;
            """)

            # Add thumbnail column if it doesn't exist
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'video_video'
                        AND column_name = 'thumbnail'
                    ) THEN
                        ALTER TABLE video_video ADD COLUMN thumbnail VARCHAR(100) NULL;
                    END IF;
                END $$;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_fix_render_database'),
    ]

    operations = [
        migrations.RunPython(add_missing_fields, migrations.RunPython.noop),
    ]
