# Generated by Django 6.0.1 on 2026-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_force_add_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(blank=True, choices=[('url', 'URL Link'), ('file', 'Uploaded File')], default='url', max_length=20, null=True),
        ),
    ]
