# Generated by Django 6.0.1 on 2026-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='translated_at',
            field=models.DateTimeField(blank=True, help_text='When the translation was last updated', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='translation_en',
            field=models.TextField(blank=True, help_text='Translation to English', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='translation_ru',
            field=models.TextField(blank=True, help_text='Translation to Russian', null=True),
        ),
    ]
