# Generated by Django 4.2.27 on 2026-01-27 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('explanation_ru', models.TextField()),
                ('explanation_kz', models.TextField()),
                ('hsk_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grammar Rule',
                'verbose_name_plural': 'Grammar Rules',
                'ordering': ['hsk_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=50)),
                ('pinyin', models.CharField(max_length=100)),
                ('translation_ru', models.CharField(max_length=255)),
                ('translation_kz', models.CharField(max_length=255)),
                ('audio_url', models.URLField(blank=True)),
                ('hsk_level', models.IntegerField(default=1)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('particle', 'Particle'), ('measure', 'Measure Word'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['hsk_level', 'frequency_rank', 'hanzi'],
                'unique_together': {('hanzi', 'pinyin')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('old_srs_level', models.IntegerField()),
                ('new_srs_level', models.IntegerField()),
                ('old_interval', models.IntegerField()),
                ('new_interval', models.IntegerField()),
                ('old_ease_factor', models.FloatField()),
                ('new_ease_factor', models.FloatField()),
                ('review_time_seconds', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='vocab.word')),
            ],
            options={
                'verbose_name': 'Review History',
                'verbose_name_plural': 'Review History',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_hanzi', models.TextField()),
                ('sentence_pinyin', models.TextField()),
                ('translation_ru', models.TextField()),
                ('translation_kz', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vocab.grammarrule')),
                ('word_examples', models.ManyToManyField(blank=True, related_name='grammar_examples', to='vocab.word')),
            ],
            options={
                'verbose_name': 'Grammar Example',
                'verbose_name_plural': 'Grammar Examples',
                'ordering': ['grammar_rule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srs_level', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('correct_reviews', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='vocab.word')),
            ],
            options={
                'verbose_name': 'Word Progress',
                'verbose_name_plural': 'Word Progress',
                'ordering': ['user', 'next_review_date'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
